package cn.huizhi;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Map;

import javax.swing.JButton;
import javax.swing.table.TableModel;

import cn.huizhi.client.Client;
import cn.huizhi.net.AppMessage;
import cn.huizhi.net.RequestCmd;
import cn.huizhi.net.RequestCmd.MessageCmd;
import cn.huizhi.util.Config;
import cn.huizhi.util.MessageBuild;

import com.google.common.collect.Maps;
import com.google.protobuf.Message;

/**
*
* @author  __USER__
*/
public class UIMain extends javax.swing.JFrame {

	private String ip = Config.getValue("ip");
	private int port = Config.getIntValue("port");
	private Client client;
	/**
	 * 
	 */
	private static final long serialVersionUID = 1677591908055410104L;
	/** Creates new form Jframe */
	public UIMain() {
		setTitle("车神来了");
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jButton3 = new javax.swing.JButton();
		jButton3.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent event) {
				TableModel tableModel = jTable1.getModel();
				int row = tableModel.getRowCount();
				Map<String, Object> map = Maps.newHashMap();
				for(int i = 0; i < row; i ++) {
					Object c1 = tableModel.getValueAt(i, 0);
					Object c2 = tableModel.getValueAt(i, 1);
					Object c3 = tableModel.getValueAt(i, 2);
					if(c3 == null) continue;
					Object value = null;
					if("INT".equals(c2)) {
						value = Integer.parseInt((String)c3);
					} else if("STRING".equals(c2)) {
						value = (String)c3;
					} else if("MESSAGE".equals(c2)) {
						value = (String)c3;
					}
					map.put((String)c1, value);
				}
				MessageCmd messageCmd = RequestCmd.getMessageCmd(button.getText());
				Message.Builder builder = messageCmd.builder;
				if(builder != null) {
					MessageBuild.build(builder, map);
				}
				if(messageCmd.cmd == AppMessage.CMD_LOGIN_BY_PID_REQ) {
					client = Client.start(ip, port);
				}
				
				if(client != null) {
					client.send(messageCmd.cmd, builder);
				}
				
			}
		});
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);


		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		
		GridLayout gridLayout = new GridLayout(RequestCmd.size(),2);
		jPanel1.setLayout(gridLayout);
		for(String name : RequestCmd.names()) {
			JButton jButton = new JButton(name);
			jButton.addActionListener(new ActionListener() {
				
				@Override
				public void actionPerformed(ActionEvent event) {
					JButton jButton = (JButton)event.getSource();
					button = jButton;
					Object[][] data = RequestCmd.getTableData(jButton.getText());
					if(data != null) {
						jTable1.setModel(new javax.swing.table.DefaultTableModel(
								data, new String[] { "field","type",
										"value" }));
					} else {
						jTable1.setModel(new javax.swing.table.DefaultTableModel(
								new Object[][]{null, null, null}, new String[] { "field","type",
										"value" }));
					}
				}
			});
			jPanel1.add(jButton);
		}
		jScrollPane1.setViewportView(jPanel1);

		jScrollPane2.setViewportView(jTable1);

		jButton3.setText("send");

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jTextArea1.setEditable(false);
		jScrollPane3.setViewportView(jTextArea1);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel3Layout
										.createSequentialGroup()
										.addGap(20, 20, 20)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jScrollPane3,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																668,
																Short.MAX_VALUE)
														.addComponent(
																jButton3,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																668,
																Short.MAX_VALUE)
														.addComponent(
																jScrollPane2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																668,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addComponent(
												jScrollPane2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												150,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButton3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane3,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												269, Short.MAX_VALUE)
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent(
						jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
						150, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18,
						18, 18).addComponent(jPanel3,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				452,
																				Short.MAX_VALUE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				22,
																				22,
																				22)
																		.addComponent(
																				jPanel3,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))
										.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				UIMain uiMain = new UIMain();
				uiMain.setLocation(200, 200);
				uiMain.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTable jTable1;
	public static javax.swing.JTextArea jTextArea1;
	private JButton button;
	// End of variables declaration//GEN-END:variables

}